// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNYgV3G3RubQlBi664yQpucnUc5j3ifhQ',
    appId: '1:45259877849:web:d68945f6dc66d49826fdc8',
    messagingSenderId: '45259877849',
    projectId: 'funfood1-847c8',
    authDomain: 'funfood1-847c8.firebaseapp.com',
    storageBucket: 'funfood1-847c8.firebasestorage.app',
    measurementId: 'G-QEN2YLG1LB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDxl0Bw-YCOpHtm1nCEhK6i9KQLN4LiKA',
    appId: '1:45259877849:android:95839e69e983d23d26fdc8',
    messagingSenderId: '45259877849',
    projectId: 'funfood1-847c8',
    storageBucket: 'funfood1-847c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1-P8EijpJs-I62X_DfvBwcByMeRobR38',
    appId: '1:45259877849:ios:f0a8670f7d1ef80c26fdc8',
    messagingSenderId: '45259877849',
    projectId: 'funfood1-847c8',
    storageBucket: 'funfood1-847c8.firebasestorage.app',
    androidClientId: '45259877849-b9fo6evlci353en7aut96268q830ofpj.apps.googleusercontent.com',
    iosClientId: '45259877849-ateqluajh2q8tclvm2a1ukoptjnv1ejp.apps.googleusercontent.com',
    iosBundleId: 'com.example.funfoodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1-P8EijpJs-I62X_DfvBwcByMeRobR38',
    appId: '1:45259877849:ios:f0a8670f7d1ef80c26fdc8',
    messagingSenderId: '45259877849',
    projectId: 'funfood1-847c8',
    storageBucket: 'funfood1-847c8.firebasestorage.app',
    androidClientId: '45259877849-b9fo6evlci353en7aut96268q830ofpj.apps.googleusercontent.com',
    iosClientId: '45259877849-ateqluajh2q8tclvm2a1ukoptjnv1ejp.apps.googleusercontent.com',
    iosBundleId: 'com.example.funfoodapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNYgV3G3RubQlBi664yQpucnUc5j3ifhQ',
    appId: '1:45259877849:web:a9d33c927c3023d226fdc8',
    messagingSenderId: '45259877849',
    projectId: 'funfood1-847c8',
    authDomain: 'funfood1-847c8.firebaseapp.com',
    storageBucket: 'funfood1-847c8.firebasestorage.app',
    measurementId: 'G-NQN4E6H85Z',
  );

}